# Generated by Django 3.2.9 on 2021-11-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('flat_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('flat_number', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('saldo_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('saldo_amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch.flats')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('payment_amount', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch.flats')),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('charge_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('charge_amount', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch.flats')),
            ],
        ),
    ]
