# Generated by Django 3.2.9 on 2021-12-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charges',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='saldo',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='charges',
            name='charge_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flats',
            name='flat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flats',
            name='flat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='flat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='saldo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
